[tox]
minversion = 4.0
envlist = molecule
skipsdist = true

[testenv]
basepython = python3
passenv = *
deps =
    -r tox-requirements.txt
commands =
    {posargs:molecule test -s podman --destroy always}