---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    molecule_inventory:
      all:
        children:
          molecule:
            hosts: {}
  tasks:
    - name: Create a container
      community.docker.docker_container:
        name: "{{ item.name }}"
        image: "{{ item.image }}"
        state: started
        command: "{{ item.command }}"
        tty: true
        detach: true
        privileged: "{{ item.privileged | default(false) }}"
      register: result
      loop: "{{ molecule_yml.platforms }}"

    - name: Fail if container is not running
      ansible.builtin.assert:
        that:
          - item.container is defined
          - item.container.State is defined
          - item.container.State.Running
        fail_msg: "Container {{ item.item.name }} is not running"
      loop: "{{ result.results }}"
      loop_control:
        label: "{{ item.item.name }}"

    - name: Add container to molecule inventory
      vars:
        inventory_partial_yaml: |
          all:
            children:
              molecule:
                hosts:
                  "{{ item.name }}":
                    ansible_connection: community.docker.docker
                    ansible_python_interpreter: "{{ '/usr/bin/python3.9' if item.name == 'oraclelinux' else '/usr/bin/python3' }}"
      ansible.builtin.set_fact:
        molecule_inventory: >-
          {{ molecule_inventory | combine(inventory_partial_yaml | from_yaml, recursive=True) }}
      loop: "{{ molecule_yml.platforms }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Dump molecule inventory
      ansible.builtin.copy:
        content: "{{ molecule_inventory | to_nice_yaml }}"
        dest: "{{ molecule_ephemeral_directory }}/inventory/molecule_inventory.yml"
        mode: "0600"

    - name: Refresh inventory
      ansible.builtin.meta: refresh_inventory