---
- name: Converge
  hosts: all
  gather_facts: true
  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}"
    # Альтернативный хостовый вариант:
    # - role: /home/vboxuser/ansible/vector-role